version: 2

sources:
  - name: silver
    database: cellular_sales
    schema: silver
    tables:
      - name: refined_customers


models: 
  - name: customer_summary
    descriptions: create summary from silver layer.
    columns: 
      - name: region
        tests:
          - unique
      - name: customer_count
        tests:
          - not_null
  - name: customer_metrics
    descriptions: customer level metrics for bi use
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: total_orders
      - name: total_spent
      - name: customer_hash
        tests:
          - not_null

          