name: 'anblicks'
version: 0.1.0
require-dbt-version: ">=1.9.0"
config-version: 2

profile: 'snowflake_profile'

# Set paths for dbt objects
analysis-paths: ["analysis"]
seed-paths: ["data"]
macro-paths: ["macros"]
model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

log-path: "logs"
target-path: "target"
clean-targets:
    - "dbt_modules"
    - "target"

# Set query behavior: prepend comments and quoting
query-comment: "{{ query_comment(node) }}"
quoting:
  database: false
  schema: false
  identifier: false


# DBT MODELS
models:
    anblicks:
        +enabled: true
        +materialized: view
        +persist_docs:
            relation: true
            columns: true
        
        silver:
            +enabled: true
            +schema: silver            
        



# Project variables
vars:
    anblicks:
        dbt_project_created_date: '2020-09-21'  # <-- Set as date when dbt project first created
        analysis_start_date: '2016-01-01'  # <-- Earliest time when organization started tracking data
        analysis_end_date: dbt_utils.current_timestamp()
        source_database: lake  # <-- Set as name of the raw source database where data is ingested


# Data seeds
seeds:  
    +quote_columns: false
    +schema: intermediate
    
    anblicks:
      +enabled: true
