snowflake_profile:
  target: "{{ env_var('ENV_NAME') }}"
  outputs:
    dev: &dev
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: cellular_sales
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: false

    qa:
      <<: *dev
      database: cellular_sales_qa

    prod:
      <<: *dev
      database: cellular_sales_prod