version: 2

sources:
  - name: bronze
    database: cellular_sales
    schema: bronze
    tables:
      - name: raw_customers
        description: "Raw customer data from external ingest"
        loaded_at_field: updated_at     # 👈 important for freshness
        freshness:
          warn_after: { count: 1060, period: day }
          error_after: { count: 1060, period: day }
        columns:
          - name: customer_id
            description: "Unique identifier for each customer"
            tests:
              - not_null
          - name: email
            description: "Customer email address"
          - name: updated_at
            description: "Timestamp when record was last updated"

      - name: raw_orders
        description: "Raw orders data from upstream source"
        loaded_at_field: last_updated   # 👈 adjust as per table
        freshness:
          warn_after: { count: 1060, period: day }
          error_after: { count: 1060, period: day }
        columns:
          - name: order_id
            description: "Order identifier"
            tests:
              - not_null
              - unique
          - name: last_updated
            description: "Timestamp for freshness check"
